local_costmap:
  global_frame: map

  rolling_window: true

  width: 6.0
  height: 6.0
  resolution: 0.05

  update_frequency: 5.0     # Map update frequency
  publish_frequency: 2.0    # Publish frequency

  plugins: 
   - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"} 
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"} 